easy_admin:
    entities:
        ArticleRdvdumois:
            class: App\Entity\ArticleRdvdumois
            list:
                fields:
                    - titre
                    - auteur
                    - { property: 'image_rdvdumois', label: 'Photo', type: 'image', base_path: '%app.path.image_rdvdumois%' }
                    - createdAt
            form:
                fields:
                    - titre
                    - chapeau
                    - auteur
                    - slug
                    - { property: 'contenu', label: 'Contenu', type: 'fos_ckeditor' }
                    - { property: 'imageFile', type: 'vich_image', label: 'Photo' }
                    - createdAt