easy_admin:
    entities:
        User:
            class: App\Entity\User
            list:
                actions: 
                    - {name: 'show', label: '', icon: 'eye', title: 'voir'}
                    - {name: '-delete'}
                    - {name: 'edit', label: '', icon: 'edit', title: 'modifier'}
                    - {name: '-new'}
                help: 'Voici la liste des utilisateurs du site'
                fields:
                    - { property: 'nom' }
                    - { property: 'prenom' }
                    - { property: 'email' }
                    - { property: 'roles' }
            form:
                fields:
                    - { property: 'nom' }
                    - { property: 'prenom' }
                    - { property: 'email' }
                    -   property: 'roles'
                        type: 'choice'
                        type_options:
                            mapped: true
                            expanded: true
                            multiple: true
                            choices: {'Rédacteur': 'ROLE_REDAC', 'Administrateur': 'ROLE_ADMIN' }