vich_uploader:
    db_driver: orm

    mappings:
        image_producteur:
            uri_prefix: '%app.path.image_producteur%'
            upload_destination: '%kernel.project_dir%/public/%app.path.image_producteur%'
        
        image_ProducteurRegion:
            uri_prefix: '%app.path.image_ProducteurRegion%'
            upload_destination: '%kernel.project_dir%/public/%app.path.image_ProducteurRegion%'
        
        image_ProducteurDirect:
            uri_prefix: '%app.path.image_ProducteurDirect%'
            upload_destination: '%kernel.project_dir%/public/%app.path.image_ProducteurDirect%'
        
        image_produit:
            uri_prefix: '%app.path.image_produit%'
            upload_destination: '%kernel.project_dir%/public/%app.path.image_produit%'
