easy_admin:
      site_name: 'ADMINISTRATION <em style="font-size:60%">LA LOCO BIO</em>'
      design:
          form_theme:
            - "@EasyAdmin/form/bootstrap_4.html.twig"
            - "@FOSCKEditor/Form/ckeditor_widget.html.twig"