easy_admin:
    entities:
        Produit:
            class: App\Entity\Produit
            list:
                title: 'Mes produits en magasin'
                fields:
                    - { property: 'is_published', label: 'Statut' }
                    - nom
                    - poids
                    - prix
                    - reference
                    - {property: 'image_produit', label: 'Photo', type: 'image', base_path: '%app.path.image_produit%' }
                actions:
                    - { name: 'show', icon: 'search', label: 'voir' }
                    - { name: 'edit',, icon: 'eye', label: 'modifier' }
                    - { name: 'delete', icon: 'trash', label: false, title: 'supprimer' }
                    - { name: 'new', label: 'Ajouter un produit', icon: 'plus', title: 'Ajouter' }

            form:
                fields:
                    - nom
                    - origine
                    - reference
                    - description
                    - { property: 'poids', help: 'indiquez le poids comme ceci : 3kg, 5kg et 10kg' }
                    - { property: 'prix', help: 'indiquez le prix comme ceci : 5,5€' }
                    - { property: 'imageFile', label: 'Photo', type: 'vich_image', base_path: '%app.path.image_produit%' }
                    - { property: 'isPublished', type: 'checkbox', label: 'Publier', help: 'Cocher la case si vous souhaitez faire apparaître le produit sur le site' }
            
            edit:
                fields:
                    - nom
                    - origine
                    - reference
                    - description
                    - { property: 'poids', help: 'indiquez le poids comme ceci : 3kg, 5kg et 10kg' }
                    - { property: 'prix', help: 'indiquez le prix comme ceci : 5,5€' }
                    - { property: 'imageFile', label: 'Photo', type: 'vich_image', base_path: '%app.path.image_produit%' }
                    - { property: 'isPublished', type: 'checkbox', label: 'Publier', help: 'Cocher la case si vous souhaitez faire apparaître le produit sur le site' }


            show:
                fields:
                    - id
                    - origine
                    - nom
                    - poids
                    - prix
                    - reference
                    - description
                    - { property: 'image_produit', label: 'Photo', type: 'image', base_path: '%app.path.image_produit%' }
                    - { property: 'createdAt', label: 'Date de Création' }
                    - { property: 'updatedAt', label: 'Date de mise à jour' }
                    - { property: 'is_published', label: 'Statut' }


