easy_admin:
    design:
        brand_color: '#49A0B5'
        menu:
            - { label: 'Nos Producteurs' }
            - { entity: 'Producteur', icon: 'seedling'}
            - { label: 'Utilisateur' }
            - { entity: 'User', icon: 'user', permission: 'ROLE_ADMIN' }

