easy_admin:
    entities:
        ArticleOnvaplusloin:
            class: App\Entity\ArticleOnvaplusloin
            list:
                title: 'Nos articles qui vont plus loin'
                fields:
                    - { property: 'is_published', label: 'Statut' }
                    - titre
                    - auteur
                    - { property: 'image_onvaplusloin', label: 'Photo', type: 'image', base_path: '%app.path.image_onvaplusloin%' }
                    - { property: 'createdAt', label: 'Date de Création' }
            form:
                title: 'Nouvelle Article'
                fields:
                    - titre
                    - chapeau
                    - auteur
                    - { property: 'contenu', label: 'Contenu', type: 'fos_ckeditor' }
                    - { property: 'imageFile', type: 'vich_image', label: 'Photo' }
                    - { property: 'isPublished', type: 'checkbox', label: 'Publier', help: 'Cocher la case si vous souhaitez faire apparaître le contenu sur le site' }
            show:
                title: 'Article (#%%entity_id%%)'
            edit:
                title: 'Modification Article (#%%entity_id%%)'
                fields:
                    - titre
                    - chapeau
                    - auteur
                    - { property: 'contenu', label: 'Contenu', type: 'fos_ckeditor' }
                    - { property: 'imageFile', type: 'vich_image', label: 'Photo' }
                    - { property: 'isPublished', type: 'checkbox', label: 'Publier', help: 'Cocher la case si vous souhaitez faire apparaître le contenu sur le site' }

