vich_uploader:
    db_driver: orm

    mappings:
        image_producteur:
            uri_prefix: '%app.path.image_producteur%'
            upload_destination: '%kernel.project_dir%/public/%app.path.image_producteur%'
